:concurrency: 2
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log

:queues:
  - mailers
  - default
:scheduler:
  :schedule:
    create_comment:
      cron: '0 * * * *'
      class: 'Schedulers::TriggerCreateComment'
